// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Promise = require("../src/Promise.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

$$Promise.map($$Promise.$$then(API.queryUser("patrick"), (function (user) {
            return API.queryComments(user.name);
          })), (function (comments) {
        return Belt_Array.forEach(comments, (function (comment) {
                      console.log(comment);
                      
                    }));
      }));

/*  Not a pure module */
