// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function PromiseBox(p) {
    this.nested = p;
};
function unbox(value) {
    if (value instanceof PromiseBox)
        return value.nested;
    else
        return value;
}
function box(value) {
    if (value != null && typeof value.then === 'function')
        return new PromiseBox(value);
    else
        return value;
}
function _make(executor) {
    return new Promise(function (resolve, reject) {
        var boxingResolve = function(value) {
            resolve(box(value));
        };
        executor(boxingResolve, reject);
    });
};
function _resolve(value) {
    return Promise.resolve(box(value));
};
function _flatThen(promise, callback) {
    return promise.then(function (value) {
        return callback(unbox(value));
    });
};
function _then(promise, callback) {
  return flatThen(promise, function(value) {
    return resolve(callback(value));
  });
}
;

function all(promises) {
  return _then(Promise.all(promises), (function (promises) {
                return promises.map(function (prim) {
                            return unbox(prim);
                          });
              }));
}

function all2(p1, p2) {
  return Promise.all([
              p1,
              p2
            ]);
}

function all3(p1, p2, p3) {
  return Promise.all([
              p1,
              p2,
              p3
            ]);
}

function all4(p1, p2, p3, p4) {
  return Promise.all([
              p1,
              p2,
              p3,
              p4
            ]);
}

function all5(p1, p2, p3, p4, p5) {
  return Promise.all([
              p1,
              p2,
              p3,
              p4,
              p5
            ]);
}

function all6(p1, p2, p3, p4, p5, p6) {
  return Promise.all([
              p1,
              p2,
              p3,
              p4,
              p5,
              p6
            ]);
}

function resolve(prim) {
  return _resolve(prim);
}

function make(prim) {
  return _make(prim);
}

function $$then(prim, prim$1) {
  return _then(prim, prim$1);
}

function flatThen(prim, prim$1) {
  return _flatThen(prim, prim$1);
}

exports.resolve = resolve;
exports.make = make;
exports.$$then = $$then;
exports.flatThen = flatThen;
exports.all = all;
exports.all2 = all2;
exports.all3 = all3;
exports.all4 = all4;
exports.all5 = all5;
exports.all6 = all6;
/*  Not a pure module */
